import {
  Stadium,
  Gate,
  Seat,
  Route,
  Parking,
  FoodVendor,
  Restroom,
  AccessibilityRoute,
  Incident,
  CrowdMetric,
  Volunteer,
  Task,
  Announcement,
  Notification,
  AISession,
  Analytics,
  AuditLog,
  UserProfile,
  RolePermission,
} from '@/domain/types';

export interface SeedDatabase {
  users: UserProfile[];
  roles: RolePermission[];
  stadiums: Stadium[];
  gates: Gate[];
  seats: Seat[];
  routes: Route[];
  parking: Parking[];
  foodVendors: FoodVendor[];
  restrooms: Restroom[];
  accessibilityRoutes: AccessibilityRoute[];
  incidents: Incident[];
  crowdMetrics: CrowdMetric[];
  volunteers: Volunteer[];
  tasks: Task[];
  announcements: Announcement[];
  notifications: Notification[];
  aiSessions: AISession[];
  analytics: Analytics[];
  auditLogs: AuditLog[];
}

export const SEED_DATA: SeedDatabase = {
  users: [
    {
      uid: 'usr_fan_1',
      email: 'carlos.rodriguez@example.com',
      displayName: 'Carlos Rodriguez (Fan)',
      role: 'FAN',
      stadiumId: 'metlife-ny-nj',
      preferredLanguage: 'en',
      accessibilityNeeds: ['STEP_FREE_PATHWAY'],
      createdAt: '2026-07-06T10:00:00Z',
      updatedAt: '2026-07-06T10:00:00Z',
    },
    {
      uid: 'usr_vol_1',
      email: 'elena.rostova@fifa2026.org',
      displayName: 'Elena Rostova (Volunteer)',
      role: 'VOLUNTEER',
      stadiumId: 'metlife-ny-nj',
      preferredLanguage: 'en',
      createdAt: '2026-07-06T09:00:00Z',
      updatedAt: '2026-07-06T09:00:00Z',
    },
    {
      uid: 'usr_ops_1',
      email: 'marcus.vance@fifa2026.org',
      displayName: 'Marcus Vance (Ops Manager)',
      role: 'OPERATIONS',
      stadiumId: 'metlife-ny-nj',
      preferredLanguage: 'en',
      createdAt: '2026-07-06T08:00:00Z',
      updatedAt: '2026-07-06T08:00:00Z',
    },
    {
      uid: 'usr_sec_1',
      email: 'sarah.jenkins@fifa2026.org',
      displayName: 'Sarah Jenkins (Security Lead)',
      role: 'SECURITY',
      stadiumId: 'metlife-ny-nj',
      preferredLanguage: 'en',
      createdAt: '2026-07-06T08:00:00Z',
      updatedAt: '2026-07-06T08:00:00Z',
    },
    {
      uid: 'usr_med_1',
      email: 'dr.aris.thorne@fifa2026.org',
      displayName: 'Dr. Aris Thorne (Medical Lead)',
      role: 'MEDICAL',
      stadiumId: 'metlife-ny-nj',
      preferredLanguage: 'en',
      createdAt: '2026-07-06T08:00:00Z',
      updatedAt: '2026-07-06T08:00:00Z',
    },
    {
      uid: 'usr_admin_1',
      email: 'admin@fifa2026.org',
      displayName: 'David Cloud (System Admin)',
      role: 'ADMIN',
      stadiumId: 'metlife-ny-nj',
      preferredLanguage: 'en',
      createdAt: '2026-07-06T07:00:00Z',
      updatedAt: '2026-07-06T07:00:00Z',
    },
  ],
  roles: [
    {
      roleId: 'FAN',
      displayName: 'Spectator / Fan',
      permissions: ['READ_MAP', 'USE_FAN_COPILOT', 'READ_ANNOUNCEMENTS'],
      allowedDashboards: ['/fan'],
      description: 'Tournament attendees requiring multilingual navigation and concessions assistance.',
    },
    {
      roleId: 'VOLUNTEER',
      displayName: 'Stadium Volunteer',
      permissions: ['READ_MAP', 'READ_TASKS', 'UPDATE_TASK', 'CREATE_INCIDENT', 'USE_VOLUNTEER_COPILOT'],
      allowedDashboards: ['/volunteer'],
      description: 'Ground staff managing crowd flow, gate assistance, and incident reporting.',
    },
    {
      roleId: 'OPERATIONS',
      displayName: 'Operations Command Lead',
      permissions: ['READ_ALL_TELEMETRY', 'RUN_WHAT_IF', 'DEPLOY_STAFF', 'BROADCAST_ANNOUNCEMENT', 'READ_ANALYTICS'],
      allowedDashboards: ['/operations', '/volunteer'],
      description: 'Command center managers monitoring 70,000+ fan ingress and gate bottleneck mitigation.',
    },
    {
      roleId: 'SECURITY',
      displayName: 'Security Command Team',
      permissions: ['READ_INCIDENTS', 'UPDATE_INCIDENTS', 'LOCKDOWN_GATES', 'TRIGGER_EVACUATION', 'BROADCAST_ANNOUNCEMENT'],
      allowedDashboards: ['/security'],
      description: 'Perimeter and gate security overseeing crowd anomalies and emergency lockdown protocols.',
    },
    {
      roleId: 'MEDICAL',
      displayName: 'Medical Triage Lead',
      permissions: ['READ_INCIDENTS', 'UPDATE_INCIDENTS', 'READ_ACCESSIBILITY_ROUTES', 'DISPATCH_TRIAGE'],
      allowedDashboards: ['/medical'],
      description: 'Paramedic and first-aid teams coordinating rapid emergency medical response.',
    },
    {
      roleId: 'ADMIN',
      displayName: 'System Administrator',
      permissions: ['FULL_ACCESS', 'MANAGE_ROLES', 'VIEW_AUDIT_LOGS', 'VIEW_BIGQUERY'],
      allowedDashboards: ['/admin', '/operations', '/fan', '/volunteer', '/security', '/medical'],
      description: 'Cloud infrastructure engineers maintaining GCP services and AI prompt governance.',
    },
  ],
  stadiums: [
    {
      stadiumId: 'metlife-ny-nj',
      name: 'MetLife Stadium (New York / New Jersey)',
      city: 'East Rutherford, NJ',
      capacity: 82500,
      centerCoordinates: { lat: 40.8135, lng: -74.0745 },
      activeTournament: 'FIFA World Cup 2026 - Final Stage',
      emergencyLockdownActive: false,
      concourseLevels: ['Lower Bowl (Sectors 101-149)', 'Mezzanine (Sectors 201-249)', 'Upper Bowl (Sectors 301-349)'],
    },
  ],
  gates: [
    {
      gateId: 'gate-a',
      stadiumId: 'metlife-ny-nj',
      name: 'Gate A (Pepsi VIP Plaza - West)',
      location: { lat: 40.8142, lng: -74.0758 },
      status: 'OPEN',
      currentWaitMinutes: 8,
      turnstileVelocityPerMin: 180,
      maxCapacityPerMin: 250,
      assignedSectors: ['101', '149', '201', '249'],
    },
    {
      gateId: 'gate-b',
      stadiumId: 'metlife-ny-nj',
      name: 'Gate B (South Plaza)',
      location: { lat: 40.8122, lng: -74.075 },
      status: 'OPEN',
      currentWaitMinutes: 12,
      turnstileVelocityPerMin: 210,
      maxCapacityPerMin: 300,
      assignedSectors: ['120', '125', '220', '225'],
    },
    {
      gateId: 'gate-c',
      stadiumId: 'metlife-ny-nj',
      name: 'Gate C (Commuter Rail Hub - East)',
      location: { lat: 40.8135, lng: -74.073 },
      status: 'CONGESTED',
      currentWaitMinutes: 42,
      turnstileVelocityPerMin: 340,
      maxCapacityPerMin: 350,
      assignedSectors: ['108', '110', '112', '114', '115'],
    },
    {
      gateId: 'gate-d',
      stadiumId: 'metlife-ny-nj',
      name: 'Gate D (Auxiliary North Plaza)',
      location: { lat: 40.8148, lng: -74.0742 },
      status: 'OPEN',
      currentWaitMinutes: 5,
      turnstileVelocityPerMin: 110,
      maxCapacityPerMin: 350,
      assignedSectors: ['130', '135', '301', '310'],
    },
  ],
  seats: [
    {
      seatId: 'sec-112-row-14-seat-5',
      stadiumId: 'metlife-ny-nj',
      sector: '112',
      row: '14',
      seatNumber: '5',
      concourseLevel: 'Lower Bowl',
      nearestGateId: 'gate-d',
      nearestRestroomId: 'restroom-110',
      nearestFoodVendorId: 'food-taco-fiesta',
      isAccessible: true,
    },
    {
      seatId: 'sec-205-row-8-seat-12',
      stadiumId: 'metlife-ny-nj',
      sector: '205',
      row: '8',
      seatNumber: '12',
      concourseLevel: 'Mezzanine',
      nearestGateId: 'gate-a',
      nearestRestroomId: 'restroom-205',
      nearestFoodVendorId: 'food-alpine-pretzel',
      isAccessible: false,
    },
  ],
  routes: [
    {
      routeId: 'gate-c-to-sec-112',
      stadiumId: 'metlife-ny-nj',
      originId: 'gate-c',
      destinationId: 'sec-112',
      distanceMeters: 450,
      estimatedWalkMinutes: 7,
      polyline: '40.8135,-74.0730|40.8135,-74.0738|40.8135,-74.0745',
      isStepFree: false,
    },
    {
      routeId: 'gate-d-to-sec-112',
      stadiumId: 'metlife-ny-nj',
      originId: 'gate-d',
      destinationId: 'sec-112',
      distanceMeters: 380,
      estimatedWalkMinutes: 4,
      polyline: '40.8148,-74.0742|40.8140,-74.0744|40.8135,-74.0745',
      isStepFree: true,
    },
  ],
  parking: [
    {
      lotId: 'lot-4-general',
      stadiumId: 'metlife-ny-nj',
      name: 'Lot 4 (General Fan Parking - Rail Hub)',
      totalSpaces: 5000,
      occupiedSpaces: 4850,
      status: 'NEAR_CAPACITY',
      shuttleConnectionToGate: 'gate-c',
      evChargingAvailable: true,
    },
    {
      lotId: 'lot-1-vip',
      stadiumId: 'metlife-ny-nj',
      name: 'Lot 1 (VIP & Accessible Parking)',
      totalSpaces: 1200,
      occupiedSpaces: 650,
      status: 'OPEN',
      shuttleConnectionToGate: 'gate-a',
      evChargingAvailable: true,
    },
  ],
  foodVendors: [
    {
      vendorId: 'food-taco-fiesta',
      stadiumId: 'metlife-ny-nj',
      name: 'Taco Fiesta & Cantina',
      sector: '110',
      concourseLevel: 'Lower Bowl',
      cuisineType: 'Mexican',
      dietaryOptions: ['VEGETARIAN', 'VEGAN', 'GLUTEN_FREE', 'HALAL'],
      currentQueueMinutes: 12,
      status: 'OPEN',
    },
    {
      vendorId: 'food-all-american',
      stadiumId: 'metlife-ny-nj',
      name: 'All-American World Cup Grill',
      sector: '105',
      concourseLevel: 'Lower Bowl',
      cuisineType: 'American Burgers & BBQ',
      dietaryOptions: ['GLUTEN_FREE'],
      currentQueueMinutes: 25,
      status: 'BUSY',
    },
    {
      vendorId: 'food-alpine-pretzel',
      stadiumId: 'metlife-ny-nj',
      name: 'Alpine Pretzel & Craft Brews',
      sector: '204',
      concourseLevel: 'Mezzanine',
      cuisineType: 'German & Snacks',
      dietaryOptions: ['VEGETARIAN'],
      currentQueueMinutes: 5,
      status: 'OPEN',
    },
  ],
  restrooms: [
    {
      restroomId: 'restroom-110',
      stadiumId: 'metlife-ny-nj',
      sector: '110',
      concourseLevel: 'Lower Bowl',
      type: 'ALL_GENDER',
      accessibleStalls: 4,
      currentQueueMinutes: 5,
      needsJanitorialService: false,
    },
    {
      restroomId: 'restroom-205',
      stadiumId: 'metlife-ny-nj',
      sector: '205',
      concourseLevel: 'Mezzanine',
      type: 'FAMILY_ACCESSIBLE',
      accessibleStalls: 2,
      currentQueueMinutes: 2,
      needsJanitorialService: false,
    },
  ],
  accessibilityRoutes: [
    {
      routeId: 'access-gate-d-to-sec-112',
      stadiumId: 'metlife-ny-nj',
      originId: 'gate-d',
      destinationId: 'sec-112',
      distanceMeters: 400,
      estimatedWalkMinutes: 6,
      polyline: '40.8148,-74.0742|40.8140,-74.0744|40.8135,-74.0745',
      isStepFree: true,
      features: ['ELEVATOR_NORTH_1', 'WIDE_CONCOURSE_RAMP', 'PRIORITY_ASSISTANCE_DESK'],
    },
  ],
  incidents: [
    {
      incidentId: 'inc-20260706-001',
      stadiumId: 'metlife-ny-nj',
      reportedByUid: 'usr_vol_1',
      incidentType: 'MEDICAL',
      location: { sector: '112', concourseLevel: 'Lower Bowl', lat: 40.8135, lng: -74.0745 },
      severity: 8,
      status: 'ACTIVE_TRIAGE',
      description: 'Spectator experiencing severe heat exhaustion, dizziness, and dehydration in Sector 112 row 14.',
      photoUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=600',
      assignedTeamId: 'med-team-beta',
      aiSummary: 'Priority 2 Medical: Heat exhaustion in Sector 112. Triage Team Beta dispatched via step-free Route D.',
      createdAt: '2026-07-06T12:15:00Z',
      resolvedAt: null,
    },
    {
      incidentId: 'inc-20260706-002',
      stadiumId: 'metlife-ny-nj',
      reportedByUid: 'usr_sec_1',
      incidentType: 'CROWD_CONGESTION',
      location: { sector: 'Gate C Plaza', concourseLevel: 'Ground Ingress', lat: 40.8135, lng: -74.073 },
      severity: 6,
      status: 'CLASSIFIED',
      description: 'Turnstile bottleneck at Gate C due to simultaneous arrival of 3 NJ Transit commuter trains.',
      assignedTeamId: 'ops-crowd-control-1',
      aiSummary: 'Gate C turnstile velocity exceeded (340/min). AI What-If recommends redirecting sectors 101-115 to Gate D.',
      createdAt: '2026-07-06T12:12:00Z',
      resolvedAt: null,
    },
  ],
  crowdMetrics: [
    {
      metricId: 'metric-gate-c-1215',
      stadiumId: 'metlife-ny-nj',
      zoneId: 'Gate C Plaza',
      timestamp: '2026-07-06T12:15:00Z',
      currentDensityPct: 88,
      riskLevel: 'RED',
      predictedWaitMinutes: 42,
      aiCongestionForecast: 'Critical bottleneck predicted within 15 mins. Reroute sectors 101-115 to Gate D auxiliary entrance immediately.',
    },
    {
      metricId: 'metric-gate-d-1215',
      stadiumId: 'metlife-ny-nj',
      zoneId: 'Gate D Auxiliary Plaza',
      timestamp: '2026-07-06T12:15:00Z',
      currentDensityPct: 35,
      riskLevel: 'GREEN',
      predictedWaitMinutes: 5,
      aiCongestionForecast: 'Optimal capacity available. Can absorb up to 15,000 rerouted spectators.',
    },
    {
      metricId: 'metric-gate-a-1215',
      stadiumId: 'metlife-ny-nj',
      zoneId: 'Gate A VIP Plaza',
      timestamp: '2026-07-06T12:15:00Z',
      currentDensityPct: 52,
      riskLevel: 'GREEN',
      predictedWaitMinutes: 8,
      aiCongestionForecast: 'Normal steady flow.',
    },
  ],
  volunteers: [
    {
      volunteerId: 'vol-881',
      uid: 'usr_vol_1',
      stadiumId: 'metlife-ny-nj',
      name: 'Elena Rostova',
      assignedZone: 'Concourse B (Sectors 108-115)',
      currentLocation: { lat: 40.8136, lng: -74.0746 },
      status: 'ON_TASK',
      certifications: ['FIRST_AID', 'MULTILINGUAL_ES_FR', 'CROWD_CONTROL'],
      activeTaskId: 'task-902',
    },
    {
      volunteerId: 'vol-882',
      uid: 'usr_vol_2',
      stadiumId: 'metlife-ny-nj',
      name: 'Marco Rossi',
      assignedZone: 'Gate C Commuter Plaza',
      currentLocation: { lat: 40.8135, lng: -74.073 },
      status: 'ON_TASK',
      certifications: ['CROWD_CONTROL', 'MULTILINGUAL_IT_ES'],
      activeTaskId: 'task-903',
    },
  ],
  tasks: [
    {
      taskId: 'task-902',
      stadiumId: 'metlife-ny-nj',
      assignedToVolunteerId: 'vol-881',
      title: 'Assist Crowd Rerouting at Gate C Fork',
      description: 'Direct spectators with lower bowl tickets (Sectors 101-115) from Gate C to Gate D auxiliary entrance.',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      checklist: [
        { item: 'Pick up digital signage wand from Concourse B locker', completed: true },
        { item: 'Position at Gate C concourse walkway fork', completed: true },
        { item: 'Redirect sector 101-115 ticket holders to Gate D (3 min walk right)', completed: false },
      ],
      createdAt: '2026-07-06T12:16:00Z',
    },
    {
      taskId: 'task-903',
      stadiumId: 'metlife-ny-nj',
      assignedToVolunteerId: 'vol-882',
      title: 'Assist Medical Triage Beta at Sector 112',
      description: 'Clear concourse walkway row 14 to allow paramedic stretcher step-free access to heat exhaustion patient.',
      priority: 'URGENT',
      status: 'IN_PROGRESS',
      checklist: [
        { item: 'Locate patient in Sector 112 Row 14 Seat 5', completed: true },
        { item: 'Provide bottled water from Concourse B supply', completed: true },
        { item: 'Guide Medical Team Beta elevator stretcher access', completed: false },
      ],
      createdAt: '2026-07-06T12:15:30Z',
    },
  ],
  announcements: [
    {
      announcementId: 'anc-20260706-001',
      stadiumId: 'metlife-ny-nj',
      targetAudience: ['ALL_STADIUM_SPECTATORS'],
      priority: 'HIGH',
      status: 'BROADCASTED',
      translations: {
        en: 'Welcome to MetLife Stadium for the FIFA World Cup 2026! To avoid delays at Gate C, please proceed to Gate D (3-minute walk right).',
        es: '¡Bienvenidos al Estadio MetLife para la Copa Mundial de la FIFA 2026! Para evitar retrasos en la Puerta C, diríjase a la Puerta D (3 minutos a la derecha).',
        fr: 'Bienvenue au stade MetLife pour la Coupe du Monde de la FIFA 2026 ! Pour éviter les retards à la porte C, veuillez vous rendre à la porte D.',
        pt: 'Bem-vindos ao Estádio MetLife para a Copa do Mundo da FIFA 2026! Para evitar atrasos no Portão C, dirija-se ao Portão D.',
        ar: 'مرحبًا بكم في ملعب ميتلايف لكأس العالم 2026! لتجنب التأخير في البوابة C، يرجى التوجه إلى البوابة D (مشيا 3 دقائق لليمين).',
        ja: 'FIFAワールドカップ2026へようこそ！ゲートCでの混雑を避けるため、右隣のゲートDへお進みください。',
        hi: 'फीफा विश्व कप 2026 के लिए मेटलाइफ स्टेडियम में आपका स्वागत है! गेट C पर देरी से बचने के लिए, कृपया गेट D पर जाएं।',
        de: 'Willkommen im MetLife Stadium zur FIFA WM 2026! Um Verzögerungen an Tor C zu vermeiden, gehen Sie bitte zu Tor D.',
      },
      broadcastedAt: '2026-07-06T12:17:00Z',
    },
  ],
  notifications: [
    {
      notificationId: 'notif-1001',
      recipientUid: 'usr_fan_1',
      title: 'Faster Entrance Available (Gate D)',
      message: 'Gate C is experiencing heavy commuter rail congestion (42 min wait). Gate D has only a 5-minute wait! Tap for step-free route.',
      actionUrl: '/fan?route=gate-d',
      read: false,
      createdAt: '2026-07-06T12:17:05Z',
    },
  ],
  aiSessions: [
    {
      sessionId: 'sess-ai-1001',
      uid: 'usr_fan_1',
      copilotType: 'FAN',
      modelUsed: 'gemini-2.5-flash',
      turnCount: 2,
      history: [
        {
          role: 'user',
          content: '¿Dónde puedo encontrar tacos vegetarianos cerca del sector 112?',
          timestamp: '2026-07-06T12:10:00Z',
        },
        {
          role: 'model',
          content: '¡Hola Carlos! Taco Fiesta & Cantina está ubicado justo en el Sector 110 (Nivel Inferior), a solo 2 minutos a pie de tu asiento. Tienen excelentes tacos vegetarianos y veganos, y el tiempo de espera actual en la cola es de solo 12 minutos.',
          timestamp: '2026-07-06T12:10:02Z',
        },
      ],
      createdAt: '2026-07-06T12:10:00Z',
    },
  ],
  analytics: [
    {
      analyticsId: 'stat-20260706-match1',
      stadiumId: 'metlife-ny-nj',
      totalSpectatorsIngress: 70000,
      avgNavigationTimeMinutes: 16.8,
      avgCongestionResponseMinutes: 8.5,
      totalAiQueriesProcessed: 45200,
      multilingualBroadcastsGenerated: 14,
      avgAiResponseLatencyMs: 1150,
      concessionWasteDivertedKg: 642,
      energyPerZoneKwh: 312,
      recordedAt: '2026-07-06T13:00:00Z',
    },
  ],
  auditLogs: [
    {
      auditId: 'audit-5592',
      stadiumId: 'metlife-ny-nj',
      actorUid: 'usr_ops_1',
      actionType: 'WHAT_IF_SIMULATION_APPLIED',
      targetResource: 'Gate C / Gate D Turnstile Re-routing',
      details: 'Operator applied AI recommendation to redirect Sectors 101-115 from Gate C to Gate D. Expected 35% congestion reduction.',
      ipAddress: '192.0.2.45',
      timestamp: '2026-07-06T12:18:00Z',
    },
  ],
};
